// automatically generated by the FlatBuffers compiler, do not modify

package com.github.peterrk.protocache.fb;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Small extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static Small getRootAsSmall(ByteBuffer _bb) { return getRootAsSmall(_bb, new Small()); }
  public static Small getRootAsSmall(ByteBuffer _bb, Small obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Small __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int i32() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean flag() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public String str() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer strAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer strInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createSmall(FlatBufferBuilder builder,
      int i32,
      boolean flag,
      int strOffset) {
    builder.startTable(3);
    Small.addStr(builder, strOffset);
    Small.addI32(builder, i32);
    Small.addFlag(builder, flag);
    return Small.endSmall(builder);
  }

  public static void startSmall(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addI32(FlatBufferBuilder builder, int i32) { builder.addInt(0, i32, 0); }
  public static void addFlag(FlatBufferBuilder builder, boolean flag) { builder.addBoolean(1, flag, false); }
  public static void addStr(FlatBufferBuilder builder, int strOffset) { builder.addOffset(2, strOffset, 0); }
  public static int endSmall(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Small get(int j) { return get(new Small(), j); }
    public Small get(Small obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

