// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// This file is generated by Apache Fory compiler.

package com.github.peterrk.protocache.fr;

import java.util.Map;
import java.util.Objects;
import org.apache.fory.annotation.ForyField;
import org.apache.fory.annotation.ForyStruct;
import org.apache.fory.annotation.Ref;
import org.apache.fory.collection.Float32List;

// Type ID 6 is specified manually.
@ForyStruct
public class ArrMap {
        // Type ID 5 is specified manually.
    @ForyStruct
    public static class Array {
        @ForyField(id = 1)
        private Float32List x;
        
    
        public Array() {
        }
    
        public Float32List getX() {
            return x;
        }
        
        public void setX(Float32List x) {
            this.x = x;
        }
        
        public byte[] toBytes() {
            return FrForyModule.getFory().serialize(this);
        }
        
        public static Array fromBytes(byte[] bytes) {
            return FrForyModule.getFory().deserialize(bytes, Array.class);
        }
        
        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append("Array(");
            sb.append("x=");
            sb.append(x);
            sb.append(")");
            return sb.toString();
        }
        
        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            Array that = (Array) o;
            return Objects.equals(x, that.x);
        }
        
        @Override
        public int hashCode() {
            return Objects.hash(x);
        }
        
    }
    
    @ForyField(id = 1)
    private Map<String, @Ref(enable=false) Array> x;
    

    public ArrMap() {
    }

    public Map<String, @Ref(enable=false) Array> getX() {
        return x;
    }
    
    public void setX(Map<String, @Ref(enable=false) Array> x) {
        this.x = x;
    }
    
    public byte[] toBytes() {
        return FrForyModule.getFory().serialize(this);
    }
    
    public static ArrMap fromBytes(byte[] bytes) {
        return FrForyModule.getFory().deserialize(bytes, ArrMap.class);
    }
    
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("ArrMap(");
        sb.append("x=");
        sb.append(x);
        sb.append(")");
        return sb.toString();
    }
    
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ArrMap that = (ArrMap) o;
        return Objects.equals(x, that.x);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(x);
    }
    
}
