// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// This file is generated by Apache Fory compiler.

package com.github.peterrk.protocache.fr;

import org.apache.fory.Fory;
import org.apache.fory.ThreadSafeFory;

public final class FrForyModule implements org.apache.fory.ForyModule {
    public static final FrForyModule INSTANCE = new FrForyModule();

    private FrForyModule() {
    }

    static ThreadSafeFory getFory() {
        return Holder.FORY;
    }

    private static ThreadSafeFory createFory() {
        return Fory.builder().withXlang(true).withCompatible(true).withRefTracking(true).withModule(INSTANCE).buildThreadSafeFory();
    }

    private static class Holder {
        private static final ThreadSafeFory FORY = createFory();
    }

    @Override
    public void install(Fory fory) {
        org.apache.fory.resolver.TypeResolver resolver = fory.getTypeResolver();
        resolver.register(Mode.class, 1L);
        resolver.register(Small.class, 2L);
        resolver.register(Vec2D.class, 4L);
        resolver.register(Vec2D.Vec1D.class, 3L);
        resolver.register(ArrMap.class, 6L);
        resolver.register(ArrMap.Array.class, 5L);
        resolver.register(Main.class, 7L);
    }
}
