// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// This file is generated by Apache Fory compiler.

package com.github.peterrk.protocache.fr;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.apache.fory.annotation.ForyField;
import org.apache.fory.annotation.ForyStruct;
import org.apache.fory.annotation.Nullable;
import org.apache.fory.annotation.Ref;
import org.apache.fory.annotation.UInt32Type;
import org.apache.fory.annotation.UInt64Type;
import org.apache.fory.collection.BoolList;
import org.apache.fory.collection.Float32List;
import org.apache.fory.collection.Float64List;
import org.apache.fory.collection.Int32List;
import org.apache.fory.collection.UInt64List;

// Type ID 7 is specified manually.
@ForyStruct
public class Main {
    @ForyField(id = 1)
    private int i32;
    
    @ForyField(id = 2)
    private @UInt32Type long u32;
    
    @ForyField(id = 3)
    private long i64;
    
    @ForyField(id = 4)
    private @UInt64Type long u64;
    
    @ForyField(id = 5)
    private boolean flag;
    
    @ForyField(id = 6)
    private Mode mode;
    
    @ForyField(id = 7)
    private String str;
    
    @ForyField(id = 8)
    private byte[] data;
    
    @ForyField(id = 9)
    private float f32;
    
    @ForyField(id = 10)
    private double f64;
    
    @ForyField(id = 11)
    private @Nullable Small object;
    
    @ForyField(id = 12)
    private Int32List i32v;
    
    @ForyField(id = 13)
    private UInt64List u64v;
    
    @ForyField(id = 14)
    private List<String> strv;
    
    @ForyField(id = 15)
    private List<byte[]> datav;
    
    @ForyField(id = 16)
    private Float32List f32v;
    
    @ForyField(id = 17)
    private Float64List f64v;
    
    @ForyField(id = 18)
    private BoolList flags;
    
    @ForyField(id = 19)
    private List<@Ref(enable=false) Small> objectv;
    
    @ForyField(id = 20)
    private @UInt32Type long tU32;
    
    @ForyField(id = 21)
    private int tI32;
    
    @ForyField(id = 22)
    private int tS32;
    
    @ForyField(id = 23)
    private @UInt64Type long tU64;
    
    @ForyField(id = 24)
    private long tI64;
    
    @ForyField(id = 25)
    private long tS64;
    
    @ForyField(id = 26)
    private Map<String, Integer> index;
    
    @ForyField(id = 27)
    private Map<Integer, @Ref(enable=false) Small> objects;
    
    @ForyField(id = 28)
    private @Nullable Vec2D matrix;
    
    @ForyField(id = 29)
    private List<@Ref(enable=false) ArrMap> vector;
    
    @ForyField(id = 30)
    private @Nullable ArrMap arrays;
    

    public Main() {
    }

    public int getI32() {
        return i32;
    }
    
    public void setI32(int i32) {
        this.i32 = i32;
    }
    
    public long getU32() {
        return u32;
    }
    
    public void setU32(long u32) {
        this.u32 = u32;
    }
    
    public long getI64() {
        return i64;
    }
    
    public void setI64(long i64) {
        this.i64 = i64;
    }
    
    public long getU64() {
        return u64;
    }
    
    public void setU64(long u64) {
        this.u64 = u64;
    }
    
    public boolean getFlag() {
        return flag;
    }
    
    public void setFlag(boolean flag) {
        this.flag = flag;
    }
    
    public Mode getMode() {
        return mode;
    }
    
    public void setMode(Mode mode) {
        this.mode = mode;
    }
    
    public String getStr() {
        return str;
    }
    
    public void setStr(String str) {
        this.str = str;
    }
    
    public byte[] getData() {
        return data;
    }
    
    public void setData(byte[] data) {
        this.data = data;
    }
    
    public float getF32() {
        return f32;
    }
    
    public void setF32(float f32) {
        this.f32 = f32;
    }
    
    public double getF64() {
        return f64;
    }
    
    public void setF64(double f64) {
        this.f64 = f64;
    }
    
    public Small getObject() {
        return object;
    }
    
    public void setObject(Small object) {
        this.object = object;
    }
    
    public Int32List getI32v() {
        return i32v;
    }
    
    public void setI32v(Int32List i32v) {
        this.i32v = i32v;
    }
    
    public UInt64List getU64v() {
        return u64v;
    }
    
    public void setU64v(UInt64List u64v) {
        this.u64v = u64v;
    }
    
    public List<String> getStrv() {
        return strv;
    }
    
    public void setStrv(List<String> strv) {
        this.strv = strv;
    }
    
    public List<byte[]> getDatav() {
        return datav;
    }
    
    public void setDatav(List<byte[]> datav) {
        this.datav = datav;
    }
    
    public Float32List getF32v() {
        return f32v;
    }
    
    public void setF32v(Float32List f32v) {
        this.f32v = f32v;
    }
    
    public Float64List getF64v() {
        return f64v;
    }
    
    public void setF64v(Float64List f64v) {
        this.f64v = f64v;
    }
    
    public BoolList getFlags() {
        return flags;
    }
    
    public void setFlags(BoolList flags) {
        this.flags = flags;
    }
    
    public List<@Ref(enable=false) Small> getObjectv() {
        return objectv;
    }
    
    public void setObjectv(List<@Ref(enable=false) Small> objectv) {
        this.objectv = objectv;
    }
    
    public long getTU32() {
        return tU32;
    }
    
    public void setTU32(long tU32) {
        this.tU32 = tU32;
    }
    
    public int getTI32() {
        return tI32;
    }
    
    public void setTI32(int tI32) {
        this.tI32 = tI32;
    }
    
    public int getTS32() {
        return tS32;
    }
    
    public void setTS32(int tS32) {
        this.tS32 = tS32;
    }
    
    public long getTU64() {
        return tU64;
    }
    
    public void setTU64(long tU64) {
        this.tU64 = tU64;
    }
    
    public long getTI64() {
        return tI64;
    }
    
    public void setTI64(long tI64) {
        this.tI64 = tI64;
    }
    
    public long getTS64() {
        return tS64;
    }
    
    public void setTS64(long tS64) {
        this.tS64 = tS64;
    }
    
    public Map<String, Integer> getIndex() {
        return index;
    }
    
    public void setIndex(Map<String, Integer> index) {
        this.index = index;
    }
    
    public Map<Integer, @Ref(enable=false) Small> getObjects() {
        return objects;
    }
    
    public void setObjects(Map<Integer, @Ref(enable=false) Small> objects) {
        this.objects = objects;
    }
    
    public Vec2D getMatrix() {
        return matrix;
    }
    
    public void setMatrix(Vec2D matrix) {
        this.matrix = matrix;
    }
    
    public List<@Ref(enable=false) ArrMap> getVector() {
        return vector;
    }
    
    public void setVector(List<@Ref(enable=false) ArrMap> vector) {
        this.vector = vector;
    }
    
    public ArrMap getArrays() {
        return arrays;
    }
    
    public void setArrays(ArrMap arrays) {
        this.arrays = arrays;
    }
    
    public byte[] toBytes() {
        return FrForyModule.getFory().serialize(this);
    }
    
    public static Main fromBytes(byte[] bytes) {
        return FrForyModule.getFory().deserialize(bytes, Main.class);
    }
    
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Main(");
        sb.append("i32=");
        sb.append(i32);
        sb.append(", ");
        sb.append("u32=");
        sb.append(u32);
        sb.append(", ");
        sb.append("i64=");
        sb.append(i64);
        sb.append(", ");
        sb.append("u64=");
        sb.append(u64);
        sb.append(", ");
        sb.append("flag=");
        sb.append(flag);
        sb.append(", ");
        sb.append("mode=");
        sb.append(mode);
        sb.append(", ");
        sb.append("str=");
        sb.append(str);
        sb.append(", ");
        sb.append("data=");
        sb.append(Arrays.toString(data));
        sb.append(", ");
        sb.append("f32=");
        sb.append(f32);
        sb.append(", ");
        sb.append("f64=");
        sb.append(f64);
        sb.append(", ");
        sb.append("object=");
        sb.append(object);
        sb.append(", ");
        sb.append("i32v=");
        sb.append(i32v);
        sb.append(", ");
        sb.append("u64v=");
        sb.append(u64v);
        sb.append(", ");
        sb.append("strv=");
        sb.append(strv);
        sb.append(", ");
        sb.append("datav=");
        sb.append(datav);
        sb.append(", ");
        sb.append("f32v=");
        sb.append(f32v);
        sb.append(", ");
        sb.append("f64v=");
        sb.append(f64v);
        sb.append(", ");
        sb.append("flags=");
        sb.append(flags);
        sb.append(", ");
        sb.append("objectv=");
        sb.append(objectv);
        sb.append(", ");
        sb.append("tU32=");
        sb.append(tU32);
        sb.append(", ");
        sb.append("tI32=");
        sb.append(tI32);
        sb.append(", ");
        sb.append("tS32=");
        sb.append(tS32);
        sb.append(", ");
        sb.append("tU64=");
        sb.append(tU64);
        sb.append(", ");
        sb.append("tI64=");
        sb.append(tI64);
        sb.append(", ");
        sb.append("tS64=");
        sb.append(tS64);
        sb.append(", ");
        sb.append("index=");
        sb.append(index);
        sb.append(", ");
        sb.append("objects=");
        sb.append(objects);
        sb.append(", ");
        sb.append("matrix=");
        sb.append(matrix);
        sb.append(", ");
        sb.append("vector=");
        sb.append(vector);
        sb.append(", ");
        sb.append("arrays=");
        sb.append(arrays);
        sb.append(")");
        return sb.toString();
    }
    
    private static boolean deepValueEquals(Object left, Object right) {
        if (left == right) {
            return true;
        }
        if (left == null || right == null) {
            return false;
        }
        if (left.getClass().isArray() || right.getClass().isArray()) {
            return deepArrayEquals(left, right);
        }
        if (left instanceof java.util.List && right instanceof java.util.List) {
            java.util.List<?> leftList = (java.util.List<?>) left;
            java.util.List<?> rightList = (java.util.List<?>) right;
            if (leftList.size() != rightList.size()) {
                return false;
            }
            for (int i = 0; i < leftList.size(); i++) {
                if (!deepValueEquals(leftList.get(i), rightList.get(i))) {
                    return false;
                }
            }
            return true;
        }
        if (left instanceof java.util.Map && right instanceof java.util.Map) {
            java.util.Map<?, ?> leftMap = (java.util.Map<?, ?>) left;
            java.util.Map<?, ?> rightMap = (java.util.Map<?, ?>) right;
            if (leftMap.size() != rightMap.size()) {
                return false;
            }
            for (java.util.Map.Entry<?, ?> entry : leftMap.entrySet()) {
                Object key = entry.getKey();
                if (!rightMap.containsKey(key)) {
                    return false;
                }
                if (!deepValueEquals(entry.getValue(), rightMap.get(key))) {
                    return false;
                }
            }
            return true;
        }
        return Objects.equals(left, right);
    }
    
    private static boolean deepArrayEquals(Object left, Object right) {
        if (left instanceof boolean[] && right instanceof boolean[]) {
            return Arrays.equals((boolean[]) left, (boolean[]) right);
        }
        if (left instanceof byte[] && right instanceof byte[]) {
            return Arrays.equals((byte[]) left, (byte[]) right);
        }
        if (left instanceof short[] && right instanceof short[]) {
            return Arrays.equals((short[]) left, (short[]) right);
        }
        if (left instanceof int[] && right instanceof int[]) {
            return Arrays.equals((int[]) left, (int[]) right);
        }
        if (left instanceof long[] && right instanceof long[]) {
            return Arrays.equals((long[]) left, (long[]) right);
        }
        if (left instanceof float[] && right instanceof float[]) {
            return Arrays.equals((float[]) left, (float[]) right);
        }
        if (left instanceof double[] && right instanceof double[]) {
            return Arrays.equals((double[]) left, (double[]) right);
        }
        if (left instanceof Object[] && right instanceof Object[]) {
            return Arrays.deepEquals((Object[]) left, (Object[]) right);
        }
        return false;
    }
    
    private static int deepValueHashCode(Object value) {
        if (value == null) {
            return 0;
        }
        if (value instanceof boolean[]) {
            return Arrays.hashCode((boolean[]) value);
        }
        if (value instanceof byte[]) {
            return Arrays.hashCode((byte[]) value);
        }
        if (value instanceof short[]) {
            return Arrays.hashCode((short[]) value);
        }
        if (value instanceof int[]) {
            return Arrays.hashCode((int[]) value);
        }
        if (value instanceof long[]) {
            return Arrays.hashCode((long[]) value);
        }
        if (value instanceof float[]) {
            return Arrays.hashCode((float[]) value);
        }
        if (value instanceof double[]) {
            return Arrays.hashCode((double[]) value);
        }
        if (value instanceof Object[]) {
            return Arrays.deepHashCode((Object[]) value);
        }
        if (value instanceof java.util.List) {
            int result = 1;
            for (Object element : (java.util.List<?>) value) {
                result = 31 * result + deepValueHashCode(element);
            }
            return result;
        }
        if (value instanceof java.util.Map) {
            int result = 0;
            for (java.util.Map.Entry<?, ?> entry : ((java.util.Map<?, ?>) value).entrySet()) {
                result += deepValueHashCode(entry.getKey()) ^ deepValueHashCode(entry.getValue());
            }
            return result;
        }
        return Objects.hashCode(value);
    }
    
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Main that = (Main) o;
        return i32 == that.i32
            && Objects.equals(u32, that.u32)
            && i64 == that.i64
            && Objects.equals(u64, that.u64)
            && flag == that.flag
            && Objects.equals(mode, that.mode)
            && Objects.equals(str, that.str)
            && Arrays.equals(data, that.data)
            && Float.compare(f32, that.f32) == 0
            && Double.compare(f64, that.f64) == 0
            && Objects.equals(object, that.object)
            && Objects.equals(i32v, that.i32v)
            && Objects.equals(u64v, that.u64v)
            && Objects.equals(strv, that.strv)
            && deepValueEquals(datav, that.datav)
            && Objects.equals(f32v, that.f32v)
            && Objects.equals(f64v, that.f64v)
            && Objects.equals(flags, that.flags)
            && Objects.equals(objectv, that.objectv)
            && Objects.equals(tU32, that.tU32)
            && tI32 == that.tI32
            && tS32 == that.tS32
            && Objects.equals(tU64, that.tU64)
            && tI64 == that.tI64
            && tS64 == that.tS64
            && Objects.equals(index, that.index)
            && Objects.equals(objects, that.objects)
            && Objects.equals(matrix, that.matrix)
            && Objects.equals(vector, that.vector)
            && Objects.equals(arrays, that.arrays);
    }
    
    @Override
    public int hashCode() {
        int result = Objects.hash(i32, u32, i64, u64, flag, mode, str, f32, f64, object, i32v, u64v, strv, deepValueHashCode(datav), f32v, f64v, flags, objectv, tU32, tI32, tS32, tU64, tI64, tS64, index, objects, matrix, vector, arrays);
        result = 31 * result + Arrays.hashCode(data);
        return result;
    }
    
}
