// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// This file is generated by Apache Fory compiler.

package com.github.peterrk.protocache.fr;

import java.util.Objects;
import org.apache.fory.annotation.ForyField;
import org.apache.fory.annotation.ForyStruct;

// Type ID 2 is specified manually.
@ForyStruct
public class Small {
    @ForyField(id = 1)
    private int i32;
    
    @ForyField(id = 2)
    private boolean flag;
    
    @ForyField(id = 4)
    private String str;
    

    public Small() {
    }

    public int getI32() {
        return i32;
    }
    
    public void setI32(int i32) {
        this.i32 = i32;
    }
    
    public boolean getFlag() {
        return flag;
    }
    
    public void setFlag(boolean flag) {
        this.flag = flag;
    }
    
    public String getStr() {
        return str;
    }
    
    public void setStr(String str) {
        this.str = str;
    }
    
    public byte[] toBytes() {
        return FrForyModule.getFory().serialize(this);
    }
    
    public static Small fromBytes(byte[] bytes) {
        return FrForyModule.getFory().deserialize(bytes, Small.class);
    }
    
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Small(");
        sb.append("i32=");
        sb.append(i32);
        sb.append(", ");
        sb.append("flag=");
        sb.append(flag);
        sb.append(", ");
        sb.append("str=");
        sb.append(str);
        sb.append(")");
        return sb.toString();
    }
    
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Small that = (Small) o;
        return i32 == that.i32
            && flag == that.flag
            && Objects.equals(str, that.str);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(i32, flag, str);
    }
    
}
