// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// This file is generated by Apache Fory compiler.

package com.github.peterrk.protocache.fr;

import java.util.List;
import java.util.Objects;
import org.apache.fory.annotation.ForyField;
import org.apache.fory.annotation.ForyStruct;
import org.apache.fory.annotation.Ref;
import org.apache.fory.collection.Float32List;

// Type ID 4 is specified manually.
@ForyStruct
public class Vec2D {
        // Type ID 3 is specified manually.
    @ForyStruct
    public static class Vec1D {
        @ForyField(id = 1)
        private Float32List x;
        
    
        public Vec1D() {
        }
    
        public Float32List getX() {
            return x;
        }
        
        public void setX(Float32List x) {
            this.x = x;
        }
        
        public byte[] toBytes() {
            return FrForyModule.getFory().serialize(this);
        }
        
        public static Vec1D fromBytes(byte[] bytes) {
            return FrForyModule.getFory().deserialize(bytes, Vec1D.class);
        }
        
        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append("Vec1D(");
            sb.append("x=");
            sb.append(x);
            sb.append(")");
            return sb.toString();
        }
        
        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            Vec1D that = (Vec1D) o;
            return Objects.equals(x, that.x);
        }
        
        @Override
        public int hashCode() {
            return Objects.hash(x);
        }
        
    }
    
    @ForyField(id = 1)
    private List<@Ref(enable=false) Vec1D> x;
    

    public Vec2D() {
    }

    public List<@Ref(enable=false) Vec1D> getX() {
        return x;
    }
    
    public void setX(List<@Ref(enable=false) Vec1D> x) {
        this.x = x;
    }
    
    public byte[] toBytes() {
        return FrForyModule.getFory().serialize(this);
    }
    
    public static Vec2D fromBytes(byte[] bytes) {
        return FrForyModule.getFory().deserialize(bytes, Vec2D.class);
    }
    
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Vec2D(");
        sb.append("x=");
        sb.append(x);
        sb.append(")");
        return sb.toString();
    }
    
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Vec2D that = (Vec2D) o;
        return Objects.equals(x, that.x);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(x);
    }
    
}
